CREATE TABLE IF NOT EXISTS `t_tutor_profile` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id` BIGINT NOT NULL COMMENT '用户ID',
    `university` VARCHAR(128) NOT NULL COMMENT '学校名称',
    `major` VARCHAR(64) DEFAULT NULL COMMENT '专业',
    `grade` VARCHAR(16) DEFAULT NULL COMMENT '年级',
    `subjects` VARCHAR(512) NOT NULL COMMENT '可辅导科目（逗号分隔）',
    `hourly_rate` INT NOT NULL COMMENT '时薪（元/小时）',
    `bio` VARCHAR(1024) DEFAULT NULL COMMENT '个人简介',
    `experience` VARCHAR(1024) DEFAULT NULL COMMENT '教学经验',
    `districts` VARCHAR(512) DEFAULT NULL COMMENT '上课区域（逗号分隔）',
    `available_times` TEXT DEFAULT NULL COMMENT '上课时段JSON',
    `rating` DECIMAL(3,2) NOT NULL DEFAULT 0.00 COMMENT '评分',
    `review_count` INT NOT NULL DEFAULT 0 COMMENT '评价数量',
    `order_count` INT NOT NULL DEFAULT 0 COMMENT '完成订单数',
    `active` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否上架',
    `deleted` INT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uk_user_id` (`user_id`),
    INDEX `idx_active_rating` (`active`, `rating`),
    INDEX `idx_subjects` (`subjects`(100))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='教员档案表';